version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    volumes:
      - /root/documents:/documents
      - /root/.kavita/data:/kavita/config
    ports:
      - "5000:5000"
