version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    volumes:
      - /root/documents:/documents
      - /root/.kavita/data:/kavita/config
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
