version: "3.9"
services:
  hiccup:
    image: bleckbeard/hiccup:latest
    container_name: hiccup
    volumes:
      - /root/.hiccup/configs/config.json:/usr/share/nginx/html/configs/config.json
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
