version: "3.9"
services:
  web:
    image: bleckbeard/hiccup:latest
    container_name: hiccup
    ports:
      - "8899:80"
    volumes:
      - /root/.hiccup/configs/config.json:/usr/share/nginx/html/configs/config.json
