services:
  web:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "${UID}:${GID}"
    ports:
      - "8081:80"
    volumes:
      - /:/srv
      - /root/.filebrowser/filebrowser.db:/database.db
