services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "${UID}:${GID}"
    volumes:
      - /:/srv
      - /root/.filebrowser/filebrowser.db:/database.db
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
