services:
  web:
    image:  portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "7999:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
